### PR TITLE
Game of life limit max size

### PR DESCRIPTION
**Pull request by Mike-3**
limited to 200

### CODE REVIEW

**Comment by S-Man42** [comment]
I believe the limit is way too low. There are incredible GoL simulations with way more cells. Is there a reason to not set the limit, lets say up to 1000 or something?

**Comment by Mike-3** [comment]
I tested it with 1000 on my smartphone. It wasn't usable. Does it work with 1000 on your phone?

But I have to say that I randomly tested and used 200. Maybe more would work. I just thought that no one would be able to enter/operate it anyway.

**Comment by t-m-z** [comment]
It depends. There are so called RLE-Files to be found in the internet which contain a starting scenario which then develops.
RLE means Run Length Encoded.


Sent from MailDroid

-----Original Message-----

**Comment by Mike-3** [comment]
We could also try to speed up the painter. Instead of 1,000,000 rectangles, only 2,000 lines.

**Comment by S-Man42** [comment]
Yes, maybe a good approach. Paint cells only if they are filled. Otherwise paint lines. Much better

**Pull request merged**
